var names = [ 'Bitcoin',
  'Ethereum',
  'Ripple',
  'Litecoin',
  'Ethereum Classic',
  'Monero',
  'Dash',
  'Augur',
  'Steem',
  'Waves',
  'MaidSafeCoin',
  'NEM',
  'Dogecoin',
  'Lisk',
  'DigixDAO',
  'Factom',
  'Gulden',
  'Stellar Lumens',
  'Peerplays',
  'BitShares',
  'Iconomi',
  'Ardor',
  'ShadowCash',
  'Bytecoin',
  'GameCredits',
  'Xaurum',
  'Storjcoin X',
  'Emercoin',
  'AntShares',
  'Counterparty',
  'Siacoin',
  'SingularDTV',
  'Tether',
  'Nxt',
  'Synereo',
  'Bitcrystals',
  'Peercoin',
  'Stratis',
  'Agoras Tokens',
  'YbCoin',
  'I/O Coin',
  'SysCoin',
  'BitcoinDark',
  'Vcash',
  'Zcash',
  'Namecoin',
  'Rubycoin',
  'Global Currency Reserve',
  'NAV Coin',
  'PotCoin',
  'BlackCoin',
  'DigiByte',
  'GridCoin',
  'Yocoin',
  'Omni',
  'SolarCoin',
  'Decred',
  'SuperNET',
  'Steem Dollars',
  'Scotcoin',
  'FuelCoin',
  'SARCoin',
  'FairCoin',
  'CureCoin',
  'NautilusCoin',
  'Swiscoin',
  'VPNCoin',
  'Expanse',
  'EarthCoin',
  'FedoraCoin',
  'Clams',
  'MonaCoin',
  'ReddCoin',
  'DigitalNote',
  'Burst',
  'Auroracoin',
  'Startcoin',
  'HitCoin',
  'Asiadigicoin',
  'Primecoin',
  'WorldCoin',
  'Radium',
  'VeriCoin',
  'Breakout Stake',
  'Vertcoin',
  'Feathercoin',
  'Quark',
  'Blocknet',
  'Nexus',
  'Boolberry',
  'DNotes',
  'HiCoin',
  'Qora',
  'MMNXT',
  'Mintcoin',
  'NuBits',
  'GoldCoin',
  'LBRY Credits',
  'Novacoin',
  'Breakout',
  'Mooncoin',
  'Darknet',
  'Obits',
  'Colossuscoin V2',
  'ZCoin',
  'Gambit',
  'Project Decorum',
  'Virtacoin',
  'BitBay',
  'Megacoin',
  'BilShares',
  'Triggers',
  'Zeitcoin',
  'Diamond',
  'Wild Beast Block',
  'EuropeCoin',
  'BoostCoin',
  'Zetacoin',
  'InstantDEX',
  'Adzcoin',
  'Viacoin',
  'Unobtanium',
  'Stealthcoin',
  'NuShares',
  'FlorinCoin',
  'Aeon',
  'Riecoin',
  'Safe Exchange Coin',
  'Infinitecoin',
  'Digitalcoin',
  'Myriad',
  'ZcCoin',
  'Pesobit',
  'Applecoin',
  'CloakCoin',
  'Bitmark',
  'FoldingCoin',
  'Voxels',
  'Circuits of Value',
  'SaluS',
  'NeuCoin',
  'bitCNY',
  'Rise',
  'HTMLCOIN',
  'EvergreenCoin',
  'UnionCoin',
  'Verge',
  'Anoncoin',
  'Horizon',
  'NobleCoin',
  'PinkCoin',
  'Energycoin',
  'OKCash',
  'Cryptonite',
  'Orbitcoin',
  'Stress',
  'Einsteinium',
  'CasinoCoin',
  'CannabisCoin',
  'NeosCoin',
  'Electronic Gulden',
  'Pandacoin',
  'Jumbucks',
  'SmileyCoin',
  'HunterCoin',
  'Pepe Cash',
  'GeoCoin',
  'Jewels',
  'TagCoin',
  'Mineum',
  'Diem',
  'Crown',
  'TrumpCoin',
  'GetGems',
  'MazaCoin',
  'Fantomcoin',
  'Shift',
  'LTBcoin',
  'SecureCoin',
  'SpreadCoin',
  'AudioCoin',
  'StabilityShares',
  'Titcoin',
  'Bitcoin Plus',
  'HempCoin',
  '1CRedit',
  'MaxCoin',
  'Sync',
  'Gycoin (Public Credits)',
  'Woodcoin',
  'vTorrent',
  'BTSR',
  'BellaCoin',
  'Magi',
  'Capricoin',
  'ECCoin',
  'SIBCoin',
  'Coin2.1',
  'Pangea Poker',
  'Bitstar',
  'Groestlcoin',
  'Creditbit',
  'HempCoin',
  'bitUSD',
  'Flycoin',
  'Quatloo',
  'DubaiCoin',
  'Bytecent',
  'VeriumReserve',
  'Krypton',
  'Qibuck',
  'BitSend',
  'Crypto Bullion',
  'Rare Pepe Party',
  'DopeCoin',
  'ArtByte',
  'WhiteCoin',
  'Joincoin',
  'NetCoin',
  'Dotcoin',
  'Sterlingcoin',
  'BitBean',
  'Cryptofund',
  'MonetaryUnit',
  'Cryptographic Anomaly',
  'Pakcoin',
  'Terracoin',
  'Levocoin',
  'Rubies',
  'Blitzcash',
  'Xiaomicoin',
  'NXTventure',
  'Cannacoin',
  'PipCoin',
  'Elcoin',
  'DeBuNe',
  'Syndicate',
  'TileCoin',
  'Swing',
  'Truckcoin',
  'Canada eCoin',
  'TeslaCoin',
  'GoldPieces',
  'LIQUID',
  'Pesetacoin',
  'Deutsche eMark',
  'DT Token',
  'UnbreakableCoin',
  'Cryptojacks',
  'BillaryCoin',
  'Sphere',
  'TransferCoin',
  'Hyper',
  'bitBTC',
  'SoonCoin',
  'PostCoin',
  'Sexcoin',
  'Karbowanec',
  'Tao',
  'Sling',
  'Wexcoin',
  'Bata',
  'CryptCoin',
  'ParkByte',
  'Memetic',
  'Sativacoin',
  'ArcticCoin',
  'GoldBlocks',
  'Moin',
  'Piggycoin',
  'HoboNickels',
  'Artex Coin',
  'Grantcoin',
  'MetalCoin',
  'PutinCoin',
  'Quotient',
  'Influxcoin',
  'Blakecoin',
  'ReeCoin',
  'ExclusiveCoin',
  'ARCHcoin',
  'bitSilver',
  'Veltor',
  'Newbium',
  'Franko',
  'UFO Coin',
  'BitBar',
  'Bottlecaps',
  'QubitCoin',
  'Universal Currency',
  'ARbit',
  'Devcoin',
  'Aricoin',
  'SOILcoin',
  'Datacoin',
  'Viral',
  'HyperStake',
  'MasterTraderCoin',
  'AmsterdamCoin',
  'GPU Coin',
  'BitSeeds',
  'GlobalBoost-Y',
  'X-Coin',
  'DigiCube',
  'SongCoin',
  'Steps',
  'Francs',
  '8Bit',
  'Cypher',
  'Neutron',
  'CryptoEscudo',
  'Destiny',
  'GCoin',
  'ApexCoin',
  'Granite',
  'Bikercoin',
  'Unitus',
  'BERNcash',
  '42 Coin',
  'LetItRide',
  'Beatcoin',
  'BiosCrypto',
  'Philosopher Stones',
  'UCoin',
  'bitEUR',
  'RevolverCoin',
  'Hommalicoin',
  'Bitcoin Scrypt',
  'UniQredit',
  'RhinoCoin',
  'AllSafe',
  'Prime-XI',
  'SpaceCoin',
  'WARP',
  'Zonecoin',
  'Metal Music Coin',
  'GamerholicCoin',
  'EGO',
  'Atomic Coin',
  'CrevaCoin',
  'Chronos',
  'Evil Coin',
  'JobsCoin',
  'LiteBar',
  'AnarchistsPrime',
  'IslaCoin',
  'Orlycoin',
  'Acoin',
  'ImpulseCoin',
  'Bantam',
  'Elementrem',
  'Emirates Gold Coin',
  'SydPak',
  'VirtualCoin',
  'Eurocoin',
  'G3N',
  'StrongHands',
  'Powercoin',
  'World Gold Coin',
  'MudraCoin',
  'PizzaCoin',
  'TRMB',
  'BlackJack',
  'KiloCoin',
  'Jinn',
  'MUSE',
  'ION',
  'PLAY',
  'BlockPay',
  'AmberCoin',
  'ICO OpenLedger',
  'Silk',
  'VootCoin',
  'I0Coin',
  'AsiaCoin',
  '2GIVE',
  'XCurrency',
  'BABCoin',
  'Ixcoin',
  'SkyNET',
  'BitSwift',
  'Synergy',
  'BritCoin',
  'BTCtalkcoin',
  'Librexcoin',
  'UltraCoin',
  'LeafCoin',
  'Coinomat',
  'MediterraneanCoin',
  'Rimbit',
  'TrustPlus',
  'Tickets',
  'IncaKoin',
  'Dimecoin',
  'Coin(O)',
  'BlueCoin',
  'RedCoin',
  'The Viral Exchange',
  'KoreCoin',
  'LiteDoge',
  'Dashcoin',
  'HOdlcoin',
  'Nxttycoin',
  'GlobalCoin',
  'BitcoinTX',
  'RussiaCoin',
  'Kobocoin',
  'SecretCoin',
  '1337',
  'Freicoin',
  'Sprouts',
  'BigUp',
  'The Cypherfunks',
  'Yacoin',
  'QuazarCoin',
  'Trollcoin',
  'FlutterCoin',
  'MojoCoin',
  'SwagBucks',
  'LottoCoin',
  'MarteXcoin',
  'Checkcoin',
  'WayGuide',
  'PayCoin',
  'TEKcoin',
  'SuperCoin',
  'SproutsExtreme',
  'GAIA',
  'PLNcoin',
  'Triangles',
  'SmartCoin',
  'VIP Tokens',
  'Ratecoin',
  'Nyancoin',
  'Bitz',
  'HamRadioCoin',
  'Gapcoin',
  'bitGold',
  'SatoshiMadness',
  'Uro',
  'BBQCoin',
  'Cashout',
  'Tigercoin',
  'BunnyCoin',
  'PetroDollar',
  'Crypto',
  'FujiCoin',
  'Emerald Crypto',
  'CageCoin',
  'OctoCoin',
  'TittieCoin',
  'CAPTcoin',
  'ZiftrCOIN',
  'Guncoin',
  'Fastcoin',
  'Joulecoin',
  'Argentum',
  'BumbaCoin',
  'AurumCoin',
  'NoLimitCoin',
  'BeaverCoin',
  'AgrolifeCoin',
  'SixEleven',
  'CoExistCoin',
  'Hundredcoin',
  'MindCoin',
  'MGW',
  'Debitcoin',
  'Cubits',
  'WMCoin',
  'Halcyon',
  'CorgiCoin',
  'Bitzeny',
  'Zayedcoin',
  'Firecoin',
  'Phoenixcoin',
  'AntiBitcoin',
  'GameBet Coin',
  'FlavorCoin',
  'VapersCoin',
  'LeaCoin',
  'Dobbscoin',
  'BlazeCoin',
  'Spots',
  'Vcoin',
  'DAPPSTER',
  'CyberCoin',
  'Evotion',
  'Kittehcoin',
  'BREAKcoin',
  'Bolivarcoin',
  'Zurcoin',
  'TrapCoin',
  'PopularCoin',
  'Prototanium',
  'MMBTCD',
  'Pospro',
  'Floz',
  'PayCon',
  'Bitcloud',
  'PrimeChain',
  'TopCoin',
  'Bitcoin 21',
  'MangoCoinz',
  'ChessCoin',
  'Dollarcoin',
  'iCash',
  'LanaCoin',
  'High Voltage',
  'Guarany',
  'Independent Money System',
  'DigitalPrice',
  'UniCoin',
  'RonPaulCoin',
  'NewYorkCoin',
  'B3Coin',
  'C-Bit',
  'ELcoin',
  'FuzzBalls',
  'GuccioneCoin',
  'NevaCoin',
  'Pulse',
  'ParallelCoin',
  'Machinecoin',
  'PosEx',
  'OsmiumCoin',
  'Cabbage',
  'PX',
  'Alexium',
  'Xonecoin',
  'Unfed',
  'DPAY',
  'TAGRcoin',
  'Comet',
  'BitQuark',
  'Photon',
  'ChainCoin',
  '808Coin',
  'Jin Coin',
  'Revenu',
  'XP',
  'Unrealcoin',
  'BitTokens',
  'Litecred',
  'MustangCoin',
  'Selfiecoin',
  'CryptBit',
  'Helleniccoin',
  'Cashcoin',
  'BowsCoin',
  'Save and Gain',
  'Shilling',
  'PonziCoin',
  'TajCoin',
  'Antilitecoin',
  'Money',
  'ImperialCoin',
  'Number7',
  'P7Coin',
  'BatCoin',
  'SwapToken',
  'CRTCoin',
  'Enigma',
  'Californium',
  'Digital Credits',
  'KhanCoin',
  'Ernus',
  '23 Skidoo',
  'SATOSHICARD',
  'HoriemonCard',
  'Pluton',
  'RoyalCoin 2',
  'NxttyACCI',
  'Forevercoin',
  'E-Dinar Coin',
  'TeslaCoilCoin',
  'BFX',
  'LEOcoin',
  'TechShares',
  'ClubCoin',
  'MaskCoin',
  'Wowecoin',
  'DynamicCoin',
  'Asset Backed Coin',
  'Index Coin',
  'The DAO',
  'EDRCoin',
  'HEAT Ledger (Pre-Launch)',
  'Mind Gene',
  'First Blood (Pre-Launch)',
  'AlpaCoin',
  'Omicron',
  'UNCoin',
  'NPCcoin',
  'GAYcoin',
  'International Diamond',
  'BigLifeCoin',
  'FuturePoints',
  'InvisibleCoin',
  'TBCoin',
  'BipCoin',
  'CaliphCoin',
  'TaoPay',
  'Happy Creator Coin',
  'DeltaCredits',
  'GBCGoldCoin',
  'Timekoin',
  'LeCoin',
  'Neptunecoin',
  'EneCoin',
  'Bitland',
  'Rhodiumcoin',
  'Alphabet Coin Fund',
  'KolschCoin',
  'LoMoCoin',
  'First Bitcoin',
  'Digitalfund',
  'Eclipse',
  'Sharkcoin',
  'BagCoin',
  'Revcoin',
  'President Johnson',
  'Peacecoin',
  'RoyalCoin',
  'Woodshares',
  'Cthulhu Offerings',
  'GotFomo',
  'CarterCoin',
  'Clinton',
  'Xaucoin',
  'ShellPay',
  'Advanced Internet Blocks',
  'UPcoin',
  'EggCoin',
  'FutCoin',
  'President Trump',
  'Rcoin',
  'GoldMaxCoin',
  'CHNCoin',
  'BitAlphaCoin',
  'IrishCoin',
  'Pentacoin',
  'Local Family Owned',
  'BitcoinFast',
  'Cleverbot',
  'OCOW',
  'TrickyCoin',
  'Psilocybin',
  'FrankyWillCoin',
  'RubleBit',
  'Kcoin',
  'Digital Bullion Gold',
  'RichCoin',
  'GameLeagueCoin',
  'FedoraShare',
  'PabyosiCoin',
  'Denarius',
  'Flaxscript',
  'Braincoin',
  'AsicCoin',
  'AvatarCoin',
  'TodayCoin',
  'Quebecoin',
  'Motocoin',
  'XAB',
  'LiteStarCoin',
  'Cycling Coin',
  'LinkedCoin',
  'Dubstep',
  'SportsCoin',
  'MobileCash',
  'Opescoin',
  'Operand',
  'Lazaruscoin',
  'UGAIN',
  'SuperStakeToken',
  'Moneta',
  'Sakuracoin',
  'TeamUp',
  'Skeincoin',
  'DarkLisk',
  'PrismChain',
  'LAthaan',
  'VegasCoin',
  'PayPeer',
  'President Clinton',
  'FitCoin',
  'GanjaCoin V2',
  'PokeChain',
  'Aces',
  'BitMoon',
  'NucleusTokens',
  'FireFlyCoin',
  'Golfcoin',
  'Tellurion',
  'Victoriouscoin',
  'ChoofCoin',
  'Cashme',
  'X2',
  'DigiEuro',
  'SuperTurboStake',
  'Valorbit',
  'TheCreed',
  'SoulCoin',
  'SafeCoin',
  'PokeCoin',
  'Xpay',
  'NUTCoin',
  'Paccoin']